---
title: "Baseball as a Motivating Example"
author: "Sajini Arumugam"
output: html_document
weight: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Assessment: Baseball as a Motivating Example

#### **Question 1**  
What is the application of statistics and data science to baseball called?
- Moneyball
- Sabermetrics    [*]
- The “Oakland A’s Approach”
- There is no specific name for this; it’s just data science.

#### **Question 2**  

Which of the following outcomes is not included in the batting average?

- A home run
- A base on balls   [*]
- An out
- A single

#### **Question 3**  

Why do we consider team statistics as well as individual player statistics?
- The success of any individual player also depends on the strength of their team.   [*]
- Team statistics can be easier to calculate.
- The ultimate goal of sabermetrics is to rank teams, not players.


#### **Question 4**  

You want to know whether teams with more at-bats per game have more runs per game.

What R code below correctly makes a scatter plot for this relationship?

```
Teams %>% filter(yearID %in% 1961:2001 ) %>%
    ggplot(aes(AB, R)) + 
    geom_point(alpha = 0.5)
```

```
[*]
Teams %>% filter(yearID %in% 1961:2001 ) %>%
    mutate(AB_per_game = AB/G, R_per_game = R/G) %>%
    ggplot(aes(AB_per_game, R_per_game)) + 
    geom_point(alpha = 0.5)
```

```
Teams %>% filter(yearID %in% 1961:2001 ) %>%
    mutate(AB_per_game = AB/G, R_per_game = R/G) %>%
    ggplot(aes(AB_per_game, R_per_game)) + 
    geom_line()
```

```
Teams %>% filter(yearID %in% 1961:2001 ) %>%
    mutate(AB_per_game = AB/G, R_per_game = R/G) %>%
    ggplot(aes(R_per_game, AB_per_game)) + 
    geom_point()
```

#### **Question 5**  

What does the variable “SOA” stand for in the Teams table?


- sacrifice out
- slides or attempts
- strikeouts by pitchers    [*]
- accumulated singles

#### **Question 6**  

Load the Lahman library. Filter the Teams data frame to include years from 1961 to 2001. Make a scatterplot of runs per game versus at bats (AB) per game.

Which of the following is true?

- There is no clear relationship between runs and at bats per game.
- As the number of at bats per game increases, the number of runs per game tends to increase.    [*]
- As the number of at bats per game increases, the number of runs per game tends to decrease.


#### **Question 7**  

Use the filtered Teams data frame from Question 6. Make a scatterplot of win rate (number of wins per game) versus number of fielding errors (E) per game.

Which of the following is true?

- There is no clear relationship between win rate and errors per game.
- As the number of errors per game increases, the win rate tends to increase.
- As the number of errors per game increases, the win rate tends to decrease.   [*]

#### **Question 8**  

Use the filtered Teams data frame from Question 6. Make a scatterplot of triples (X3B) per game versus doubles (X2B) per game.

Which of the following is true?

- There is no clear relationship between doubles per game and triples per game.    [*]
- As the number of doubles per game increases, the number of triples per game tends to increase.
- As the number of doubles per game increases, the number of triples per game tends to decrease.


