---
title: "2.1 - Reshaping data"
author: "Sajini Arumugam"
output: html_document
weight: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Assessment Part 1: Reshaping Data

Part 1 consists of 8 questions are conceptual questions about tidy data and reshaping data. They do not necessarily require R, but you may benefit from checking your work on the console.

Part 2 consists of 7 questions which require you to write code in R to apply the new concepts about tidy data and reshaping 

#### **Question 1**  
A collaborator sends you a file containing data for three years of average race finish times.

```
age_group,2015,2016,2017
20,3:46,3:22,3:50
30,3:50,3:43,4:43
40,4:39,3:49,4:51
50,4:48,4:59,5:01
```
Are these data considered “tidy” in R? Why or why not?

- Yes. These data are considered “tidy” because each row contains unique observations.
- Yes. These data are considered “tidy” because there are no missing data in the data frame.
- No. These data are not considered “tidy” because the variable “year” is stored in the header.    [*]
- No. These data are not considered “tidy” because there are not an equal number of columns and rows.

#### **QUestion 2**  
Below are four versions of the same dataset. Which one is in a tidy format?

```
state      abb region  population total
Alabama     AL	South	4779736	  135
Alaska      AK   West 	710231	  19
Arizona     AZ   West	6392017   232
Arkansas    AR  South	2915918	  93
California  CA   West   37253956  1257
Colorado    CO   West	5029196	  65
```

#### **Question 3**  
Your file called “times.csv” has age groups and average race finish times for three years of marathons.

age_group,2015,2016,2017
20,3:46,3:22,3:50
30,3:50,3:43,4:43
40,4:39,3:49,4:51
50,4:48,4:59,5:01

You read in the data file using the following command.

```
d <- read_csv("times.csv")
```
Which commands will help you “tidy” the data?

```

tidy_data <- d %>%
    gather(year, time, `2015`:`2017`)
```

#### **Question 4**  
You have a dataset on U.S. contagious diseases, but it is in the following wide format:

```
> head(dat_wide)
state year population HepatitisA Mumps Polio Rubella
Alabama 1990    4040587      86	   19    76    1
Alabama 1991    4066003      39	   14    65    0
Alabama 1992    4097169      35	   12    24    0
Alabama 1993    4133242      40	   22    67    0
Alabama 1994    4173361      72	   12    39    0
Alabama 1995    4216645      75     2    38    0
```
You want to transform this into a tidy dataset, with each row representing an observation of the incidence of each specific disease (as shown below):

```
> head(dat_tidy)
state   year  population  disease  count
Alabama 1990	4040587 HepatitisA	86
Alabama 1991	4066003 HepatitisA	39
Alabama 1992	4097169 HepatitisA	35
Alabama 1993	4133242 HepatitisA	40
Alabama 1994	4173361 HepatitisA	72
Alabama 1995	4216645 HepatitisA	75
```
Which of the following commands would achieve this transformation to tidy the data?

```
dat_tidy <- dat_wide %>%
    gather(key = disease, value = count, HepatitisA:Rubella)
```

#### **Question 5**  
You have successfully formatted marathon finish times into a tidy object called tidy_data. The first few lines are shown below.

```
age_group year   time
20        2015   03:46
30        2015   03:50
40        2015   04:39
50        2015   04:48
20        2016   03:22
```
Select the code that converts these data back to the wide format, where each year has a separate column.

```
tidy_data %>% spread(time, year)
tidy_data %>% spread(year, time)    [*]
tidy_data %>% spread(year, age_group)   
tidy_data %>% spread(time, year, `2015`:`2017`)
```

#### **Question 6**  
You have the following dataset:

```
 head(dat)
state   abb region    	var   people
Alabama  AL  South population 4779736
Alabama  AL  South  	total 	  135
Alaska   AK   West population  710231
Alaska   AK   West  	total  	   19
Arizona  AZ   West population 6392017
Arizona  AZ   West  	total 	  232
```
You would like to transform it into a dataset where population and total are each their own column (shown below):

```
state      abb region population total
Alabama     AL  South	4779736   135
Alaska      AK   West 	 710231    19
Arizona     AZ   West	6392017   232
Arkansas    AR  South	2915918    93
California  CA   West  37253956  1257
Colorado    CO   West	5029196	   65
```
Which code would best accomplish this?

```
dat_tidy <- dat %>% spread(key = var, value = people)   [*]
dat_tidy <- dat %>% spread(key = state:region, value = people)
dat_tidy <- dat %>% spread(key = people, value = var)
dat_tidy <- dat %>% spread(key = region, value = people)
```

#### **Question 7**

A collaborator sends you a file containing data for two years of average race finish times, "times.csv":

```
age_group,2015_time,2015_participants,2016_time,2016_participants
20,3:46,54,3:22,62
30,3:50,60,3:43,58
40,4:39,29,3:49,33
50,4:48,10,4:59,14
```
Which of the answers below best makes the data tidy?

```
tidy_data <- d %>%
    gather(key = “key”, value = “value”, -age_group) %>%
    separate(col = key, into = c(“year”, “variable_name”), sep = “_”) %>% 
    spread(key = variable_name, value = value)
```

#### **Question 8**  
You are in the process of tidying some data on heights, hand length, and wingspan for basketball players in the draft. Currently, you have the following:

```
> head(stats)
key               value
allen_height      75
allen_hand_length 8.25
allen_wingspan	  79.25
bamba_height      83.25
bamba_hand_length 9.75
bamba_wingspan    94
```
Select all of the correct commands below that would turn this data into a “tidy” format with columns "height", "hand_length" and "wingspan".

```
tidy_data <- stats %>%
    separate(col = key, into = c("player", "variable_name"), sep = "_", extra = "merge") %>% 
    spread(key = variable_name, value = value)
```

### Assessment Part 2: Reshaping Data

Use the following libraries for these questions:

library(tidyverse)
library(dslabs)

#### **Question 9**  
Examine the built-in dataset co2. This dataset comes with base R, not dslabs - just type co2 to access the dataset.

Is co2 tidy? Why or why not?

- co2 is tidy data: it has one year for each row.
- co2 is tidy data: each column is a different month.
- co2 is not tidy: there are multiple observations per column.
- co2 is not tidy: to be tidy we would have to wrangle it to have three columns (year, month and value), and then each co2 observation would have a row.   [*]

#### **Question 10**  
Run the following command to define the co2_wide object:

```
co2_wide <- data.frame(matrix(co2, ncol = 12, byrow = TRUE)) %>% 
      setNames(1:12) %>%
    mutate(year = as.character(1959:1997))
```
Use the gather function to make this dataset tidy. Call the column with the CO2 measurements co2 and call the month column month. Name the resulting object co2_tidy.

Which code would return the correct tidy format?

- co2_tidy <- gather(co2_wide,month,co2,year)
- co2_tidy <- gather(co2_wide,co2,month,-year)
- co2_tidy <- gather(co2_wide,co2,month,year)
- co2_tidy <- gather(co2_wide,month,co2,-year)    [*]

#### **Question 11**  
Use co2_tidy to plot CO2 versus month with a different curve for each year:

```
co2_tidy %>% ggplot(aes(as.numeric(month), co2, color = year)) + geom_line()
```

What can be concluded from this plot?

- CO2 concentrations increased monotonically (never decreased) from 1959 to 1997.
- CO2 concentrations are highest around May and the yearly average increased from 1959 to 1997.   [*]
- CO2 concentrations are highest around October and the yearly average increased from 1959 to 1997.
- Yearly average CO2 concentrations have remained constant over time.

#### **Question 12**  
Load the built-in admissions dataset, which contains college admission information for men and women across six majors, and remove the applicants percentage column:

```
library(dslabs)
data(admissions)
dat <- admissions %>% select(-applicants)
```
Your goal is to get the data in the shape that has one row for each major, like this:

```
major  men   women
A      62    82		
B      63    68		
C      37    34		
D      33    35		
E      28    24		
F       6     7	
```
Which command could help you to wrangle the data into the desired format?

- dat_tidy <- spread(dat, major, admitted)
- dat_tidy <- spread(dat, gender, major)
- dat_tidy <- spread(dat, gender, admitted)   [*]
- dat_tidy <- spread(dat, admitted, gender)

#### **Question 13**  
Now use the admissions dataset to create the object tmp, which has columns major, gender, key and value:

```
tmp <- gather(admissions, key, value, admitted:applicants)
tmp
```
Combine the key and gender and create a new column called column_name to get a variable with the following values: admitted_men, admitted_women, applicants_men and applicants_women. Save the new data as tmp2.

Which command could help you to wrangle the data into the desired format?

- tmp2 <- spread(tmp, column_name, key, gender)
- tmp2 <- gather(tmp, column_name, c(gender,key))
- tmp2 <- unite(tmp, column_name, c(gender, key))
- tmp2 <- spread(tmp, column_name, c(key,gender))
- tmp2 <- unite(tmp, column_name, c(key, gender))   [*]

#### **Question 14**  
Which function can reshape tmp2 to a table with six rows and five columns named major, admitted_men, admitted_women, applicants_men and applicants_women?

- gather
- spread    [*]
- separate
- unite
