---
title: "2.2 - Combining tables"
author: "Sajini Arumugam"
output: html_document
weight: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Assessment: Combining Tables  

#### **Question 1**  
You have created data frames tab1 and tab2 of state population and election data, similar to our module videos:
```
> tab1
state   	     population
Alabama             4779736
Alaska     	         710231
Arizona    	        6392017
Delaware     	     897934
District of Columbia 601723

> tab2
state  electoral_votes
Alabama      9
Alaska       3
Arizona     11
California  55
Colorado     9
Connecticut  7

> dim(tab1)
[1] 5 2

> dim(tab2)
[1] 6 2
```
What are the dimensions of the table dat, created by the following command?

```
dat <- left_join(tab1, tab2, by = “state”)
```
- 3 rows by 3 columns
- 5 rows by 2 columns
- 5 rows by 3 columns   [*]
- 6 rows by 3 columns

#### **Question 2**  
We are still using the tab1 and tab2 tables shown in question 1. What join command would create a new table “dat” with three rows and two columns?

- dat <- right_join(tab1, tab2, by = “state”)
- dat <- full_join(tab1, tab2, by = “state”)
- dat <- inner_join(tab1, tab2, by = “state”)
- dat <- semi_join(tab1, tab2, by = “state”)    [*]

#### **Question 3**  
Which of the following are real differences between the join and bind functions?

- Binding functions combine by position, while join functions match by variables.   [*]
- Joining functions can join datasets of different dimensions, but the bind functions must match on the appropriate dimension (either same row or column numbers).   [*]
- Bind functions can combine both vectors and dataframes, while join functions work for only for dataframes.    [*]
- The join functions are a part of the dplyr package and have been optimized for speed, while the bind functions are inefficient base functions.

#### **Question 4**  
We have two simple tables, shown below, with columns x and y:
```
> df1
 x     y    
 a     a    
 b     a    

> df2
 x     y    
 a     a    
 a     b 
 ```
Which command would result in the following table?
```
> final
 x     y    
 b     a   
```
- final <- union(df1, df2)
- final <- setdiff(df1, df2)    [*]
- final <- setdiff(df2, df1)
- final <- intersect(df1, df2)

Introduction to Questions 5-7
Install and load the Lahman library. This library contains a variety of datasets related to US professional baseball. We will use this library for the next few questions and will discuss it more extensively in the Regression course. For now, focus on wrangling the data rather than understanding the statistics.

The Batting data frame contains the offensive statistics for all baseball players over several seasons.  Filter this data frame to define top as the top 10 home run (HR) hitters in 2016:

library(Lahman)
top <- Batting %>% 
  filter(yearID == 2016) %>%
  arrange(desc(HR)) %>%    # arrange by descending HR count
  slice(1:10)    # take entries 1-10
top %>% as_tibble()
Also Inspect the Master data frame, which has demographic information for all players:

Master %>% as_tibble()

#### **Question 5**  

Use the correct join or bind function to create a combined table of the names and statistics of the top 10 home run (HR) hitters for 2016. This table should have the player ID, first name, last name, and number of HR for the top 10 players. Name this data frame top_names.

Identify the join or bind that fills the blank in this code to create the correct table:

```
top_names <- top %>% ___________________ %>%
    select(playerID, nameFirst, nameLast, HR)
```
Which bind or join function fills the blank to generate the correct table?

- rbind(Master)
- cbind(Master)
- left_join(Master)   [*]
- right_join(Master)
- full_join(Master)
- anti_join(Master)

#### **Question 6**  
Inspect the Salaries data frame. Filter this data frame to the 2016 salaries, then use the correct bind join function to add a salary column to the top_names data frame from the previous question. Name the new data frame top_salary. Use this code framework:
```
top_salary <- Salaries %>% filter(yearID == 2016) %>%
  ______________ %>%
  select(nameFirst, nameLast, teamID, HR, salary)
```

Which bind or join function fills the blank to generate the correct table?
- right_join(top_names)


#### **Question 7**  
Inspect the AwardsPlayers table. Filter awards to include only the year 2016.

How many players from the top 10 home run hitters won at least one award in 2016?

```
Awards_2016 <- AwardsPlayers %>% filter(yearID == 2016)
length(intersect(Awards_2016$playerID, top_names$playerID))
```

How many players won an award in 2016 but were not one of the top 10 home run hitters in 2016?
```
length(setdiff(Awards_2016$playerID, top_names$playerID))
```

### Assessment: Web Scraping

Introduction: Questions 1-3
Load the following web page, which contains information about Major League Baseball payrolls, into R: https://web.archive.org/web/20181024132313/http://www.stevetheump.com/Payrolls.htm

library(rvest)
url <- "https://web.archive.org/web/20181024132313/http://www.stevetheump.com/Payrolls.htm"
h <- read_html(url)
We learned that tables in html are associated with the table node.  Use the html_nodes function and the table node type to extract the first table. Store it in an object nodes:

nodes <- html_nodes(h, "table")
The html_nodes function returns a list of objects of class xml_node. We can see the content of each one using, for example, the html_text function. You can see the content for an arbitrarily picked component like this:

html_text(nodes[[8]])
If the content of this object is an html table, we can use the html_table function to convert it to a data frame:

html_table(nodes[[8]])
You will analyze the tables from this HTML page over questions 1-3.

#### **Question 1**  
Many tables on this page are team payroll tables, with columns for rank, team, and one or more money values. Note that not all tables have the same column names.

Convert the first three tables in nodes to data frames and inspect them.

Which of the first three nodes are tables of team payroll?

- None of the below
- Table 1
- Table 2   [*]
- Table 3   [*]

```
sapply(nodes[1:3], html_table)    # 2, 3 give tables with payroll info
```

#### **Question 2**  
For the last 3 components of nodes, which of the following are true? (Check all correct answers.)

- All three entries are tables. correct   [*]
- All three entries are tables of payroll per team.
- The last entry shows the average across all teams through time, not payroll per team. correct   [*]
- None of the three entries are tables of payroll per team.

```
html_table(nodes[[length(nodes)-2]])
html_table(nodes[[length(nodes)-1]])
html_table(nodes[[length(nodes)]])
```

#### **Question 3**  
Create a table called tab_1 using entry 10 of nodes. Create a table called tab_2 using entry 19 of nodes.

Note that the column names should be c("Team", "Payroll", "Average"). You can see that these column names are actually in the first data row of each table, and that tab_1 has an extra first column No. that should be removed so that the column names for both tables match.

Remove the extra column in tab_1, remove the first row of each dataset, and change the column names for each table to c("Team", "Payroll", "Average"). Use a full_join by the Team to combine these two tables.

How many rows are in the joined data table?

```
tab_1 <- html_table(nodes[[10]])
tab_2 <- html_table(nodes[[19]])
col_names <- c("Team", "Payroll", "Average")
tab_1 <- tab_1[-1, -1]
tab_2 <- tab_2[-1,]
names(tab_2) <- col_names
names(tab_1) <- col_names
full_join(tab_1,tab_2, by = "Team")
```
Introduction: Questions 4 and 5

The Wikipedia page on opinion polling for the Brexit referendum, in which the United Kingdom voted to leave the European Union in June 2016, contains several tables. One table contains the results of all polls regarding the referendum over 2016:

Use the rvest library to read the HTML from this Wikipedia page (make sure to copy both lines of the URL):

library(rvest)
library(tidyverse)
url <- "https://en.wikipedia.org/w/index.php?title=Opinion_polling_for_the_United_Kingdom_European_Union_membership_referendum&oldid=896735054"

#### **Question 4**  
Assign tab to be the html nodes of the "table" class.

How many tables are in this Wikipedia page?

```
tab <- read_html(url) %>% html_nodes("table")
length(tab)
```

#### **Question 5**  
Inspect the first several html tables using html_table with the argument fill=TRUE (you can read about this argument in the documentation). Find the first table that has 9 columns with the first column named "Date(s) conducted".

What is the first table number to have 9 columns where the first column is named "Date(s) conducted"?

```
tab[[5]] %>% html_table(fill = TRUE) %>% names()    # inspect column names
```

