---
title: "3.1 - String Processing"
author: "Sajini Arumugam"
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Assessment: String Processing Part 1

#### **Question 1**  
Which of the following is NOT an application of string parsing?

- Removing unwanted characters from text.
- Extracting numeric values from text.
- Formatting numbers and characters so they can easily be displayed in deliverables like papers and presentations.    [*]
- Splitting strings into multiple values.

#### **Question 2**  
Which of the following commands would not give you an error in R?

- cat(" LeBron James is 6’8\" ")    [*]
- cat(' LeBron James is 6'8" ')
- cat(` LeBron James is 6'8" `)
- cat(" LeBron James is 6\’8" ")

#### **Question 3**  
Which of the following are advantages of the stringr package over string processing functions in base R? Select all that apply.

- Base R functions are rarely used for string processing by data scientists so it’s not worth learning them.
- Functions in stringr all start with “str_”, which makes them easy to look up using autocomplete.    [*]
- Stringr functions work better with pipes.   [*]
- The order of arguments is more consistent in stringr functions than in base R.   [*]

#### **Question 4**  
You have a dataframe of monthly sales and profits in R

```
> head(dat)
# A tibble: 5 x 3
Month     Sales     Profit 
<chr>     <chr>     <chr>  
January   $128,568  $16,234
February  $109,523  $12,876
March     $115,468  $17,920
April     $122,274  $15,825
May       $117,921  $15,437
```
Which of the following commands could convert the sales and profits columns to numeric? Select all that apply.

```
dat %>% mutate_at(2:3, parse_number)
```
```
dat %>% mutate_at(2:3, as.numeric)
```
```
dat %>% mutate_all(parse_number)
```
```
dat %>% mutate_at(2:3, funs(str_replace_all(., c("\\$|,"), ""))) %>% 
    mutate_at(2:3, as.numeric)
``` 

***


### **Assessment: String Processing Part 2**  

#### **Question 1**  

```
not_inches <- function(x, smallest = 50, tallest = 84) {
  inches <- suppressWarnings(as.numeric(x))
  ind <- is.na(inches) | inches < smallest | inches > tallest 
  ind
}
```
In this function, what TWO types of values are identified as not being correctly formatted in inches?

- Values that specifically contain apostrophes (‘), periods (.) or quotations (“).
- Values that result in NA’s when converted to numeric    [*]
- Values less than 50 inches or greater than 84 inches    [*]
- Values that are stored as a character class, because most are already classed as numeric.

#### **Question 2**  
Which of the following arguments, when passed to the function not_inches, would return the vector c(FALSE)?


- c(175)
- c(“5’8\””)
- c(70)   [*]
- c(85) (the height of Shaquille O'Neal in inches)

#### **Question 3**  
Our function not_inches returns the object ind. Which answer correctly describes ind?


- ind is a logical vector of TRUE and FALSE, equal in length to the vector x (in the arguments list). TRUE indicates that a height entry is incorrectly formatted.   [*]
- ind is a logical vector of TRUE and FALSE, equal in length to the vector x (in the arguments list). TRUE indicates that a height entry is correctly formatted.
- ind is a data frame like our reported_heights table but with an extra column of TRUE or FALSE. TRUE indicates that a height entry is incorrectly formatted.
- ind is a numeric vector equal to reported_heights$heights but with incorrectly formatted heights replaced with NAs.

#### **Question 4**  

Given the following code

> s
[1] "70"       "5 ft"     "4'11"     ""         "."        "Six feet"
What pattern vector yields the following result?
```
str_view_all(s, pattern)
70
5 ft
4’11
.
Six feet
```

- pattern <- "\\d|ft"   [*]
- pattern <- "\d|ft"
- pattern <- "\\d\\d|ft"
- pattern <- "\\d|feet"

#### **Question 5**  

You enter the following set of commands into your R console. What is your printed result?

```
> animals <- c("cat", "puppy", "Moose", "MONKEY")
> pattern <- "[a-z]"
> str_detect(animals, pattern)
```

- TRUE
- TRUE TRUE TRUE TRUE
- TRUE TRUE TRUE FALSE    [*]
- TRUE TRUE FALSE FALSE

#### **Question 6**

You enter the following set of commands into your R console. What is your printed result?

```
> animals <- c("cat", "puppy", "Moose", "MONKEY")
> pattern <- "[A-Z]$"
> str_detect(animals, pattern)
```

- FALSE FALSE FALSE FALSE
- FALSE FALSE TRUE TRUE
- FALSE FALSE FALSE TRUE    [*]
- TRUE TRUE TRUE FALSE

#### **Question 7**  

You enter the following set of commands into your R console. What is your printed result?

```
> animals <- c("cat", "puppy", "Moose", "MONKEY")
> pattern <- "[a-z]{4,5}"
> str_detect(animals, pattern)
```

- FALSE TRUE TRUE FALSE   [*]
- TRUE TRUE FALSE FALSE
- FALSE FALSE FALSE TRUE
- TRUE TRUE TRUE FALSE

#### **Question 8**  

Given the following code

```
animals <- c("moose", "monkey", "meerkat", "mountain lion")
```
Which TWO “pattern” vectors would yield the following result?

```
> str_detect(animals, pattern)
[1] TRUE TRUE TRUE TRUE
```

- pattern <- “mo*”    []
- pattern <- “mo?”    [*]
- pattern <- “mo+”
- pattern <- “moo*”

#### **Question 9**  

You are working on some data from different universities. You have the following vector:

```
> schools
[1] "U. Kentucky"                 "Univ New Hampshire"          "Univ. of Massachusetts"      "University Georgia"         
[5] "U California"                "California State University"
```

You want to clean this data to match the full names of each university:

```
> final
[1] "University of Kentucky"      "University of New Hampshire" "University of Massachusetts" "University of Georgia"         
[5] "University of California"    "California State University"
```
What of the following commands could accomplish this?

```
schools %>% 
    str_replace("Univ\\.?|U\\.?", "University ") %>% 
    str_replace("^University of |^University ", "University of ")
```
```
[*]
schools %>% 
    str_replace("^Univ\\.?\\s|^U\\.?\\s", "University ") %>% 
    str_replace("^University of |^University ", "University of ")
 ```
 ```
schools %>% 
    str_replace("^Univ\\.\\s|^U\\.\\s", "University") %>% 
    str_replace("^University of |^University ", "University of ")
 ```
 ```
schools %>% 
    str_replace("^Univ\\.?\\s|^U\\.?\\s", "University") %>% 
    str_replace("University ", "University of ")
```    

#### **Question 10**  

Rather than using the pattern_with_groups vector from the video, you accidentally write in the following code:

```
problems <- c("5.3", "5,5", "6 1", "5 .11", "5, 12")
pattern_with_groups <- "^([4-7])[,\\.](\\d*)$"
str_replace(problems, pattern_with_groups, "\\1'\\2")
```
What is your result?

```
[*]
[1] "5'3" "5'5" "6 1" "5 .11" "5, 12"
```
```
[1] "5.3" "5,5" "6 1" "5 .11" "5, 12"

```
```
[1] "5'3" "5'5" "6'1" "5 .11" "5, 12"
```
```
[1] "5'3" "5'5" "6'1" "5’11" "5’12"
```

#### **Question 11**  

You notice your mistake and correct your pattern regex to the following

```
problems <- c("5.3", "5,5", "6 1", "5 .11", "5, 12")
pattern_with_groups <- "^([4-7])[,\\.\\s](\\d*)$"
str_replace(problems, pattern_with_groups, "\\1'\\2")
```

What is your result?

```
[1] "5'3" "5'5" "6 1" "5 .11" "5, 12"
```
```
[1] "5.3" "5,5" "6 1" "5 .11" "5, 12"

```
```
[*]
[1] "5'3" "5'5" "6'1" "5 .11" "5, 12"
```
```
[1] "5'3" "5'5" "6'1" "5’11" "5’12"
```

#### **Question 12**  

In our example, we use the following code to detect height entries that do not match our pattern of x’y”.

```
converted <- problems %>% 
  str_replace("feet|foot|ft", "'") %>% 
  str_replace("inches|in|''|\"", "") %>% 
  str_replace("^([4-7])\\s*[,\\.\\s+]\\s*(\\d*)$", "\\1'\\2")

pattern <- "^[4-7]\\s*'\\s*\\d{1,2}$"
index <- str_detect(converted, pattern)
converted[!index]
```

Which answer best describes the differences between the regex string we use as an argument in 

```
str_replace("^([4-7])\\s*[,\\.\\s+]\\s*(\\d*)$", "\\1'\\2") and the regex string in pattern <- "^[4-7]\\s*'\\s*\\d{1,2}$"?
```

- The regex used in str_replace looks for either a comma, period or space between the feet and inches digits, while the pattern regex just looks for an apostrophe; the regex in str_replace allows for one or more digits to be entered as inches, while the pattern regex only allows for one or two digits.
- The regex used in str_replace allows for additional spaces between the feet and inches digits, but the pattern regex does not.
- The regex used in str_replace looks for either a comma, period or space between the feet and inches digits, while the pattern regex just looks for an apostrophe; the regex in str_replace allows none or more digits to be entered as inches, while the pattern regex only allows for the number 1 or 2 to be used.
- The regex used in str_replace looks for either a comma, period or space between the feet and inches digits, while the pattern regex just looks for an apostrophe; the regex in str_replace allows for none or more digits to be entered as inches, while the pattern regex only allows for one or two digits.    [*]


#### **Question 13**  

You notice a few entries that are not being properly converted using your str_replace and str_detect code

:

```
yes <- c("5 feet 7inches", “5 7”)
no <- c("5ft 9 inches", "5 ft 9 inches")
s <- c(yes, no)

converted <- s %>% 
  str_replace("feet|foot|ft", "'") %>% 
  str_replace("inches|in|''|\"", "") %>% 
  str_replace("^([4-7])\\s*[,\\.\\s+]\\s*(\\d*)$", "\\1'\\2")

pattern <- "^[4-7]\\s*'\\s*\\d{1,2}$"
str_detect(converted, pattern)
[1]  TRUE TRUE FALSE FALSE
```

It seems like the problem may be due to spaces around the words feet|foot|ft and inches|in. What is another way you could fix this problem?


```
[*]
converted <- s %>% 
    str_replace("\\s*(feet|foot|ft)\\s*", "'") %>% 
    str_replace("\\s*(inches|in|''|\")\\s*", "") %>% 
    str_replace("^([4-7])\\s*[,\\.\\s+]\\s*(\\d*)$", "\\1'\\2")
 ```
 ```
 converted <- s %>% 
    str_replace("\\s+feet|foot|ft\\s+”, "'") %>% 
    str_replace("\\s+inches|in|''|\"\\s+", "") %>% 
    str_replace("^([4-7])\\s*[,\\.\\s+]\\s*(\\d*)$", "\\1'\\2")
 ```
 ```
 converted <- s %>% 
    str_replace("\\s*|feet|foot|ft", "'") %>% 
    str_replace("\\s*|inches|in|''|\"", "") %>% 
    str_replace("^([4-7])\\s*[,\\.\\s+]\\s*(\\d*)$", "\\1'\\2") 
 ```
 ```
 converted <- s %>% 
    str_replace_all(“\\s”, “”) %>% 
    str_replace("\\s|feet|foot|ft", "'") %>% 
    str_replace("\\s|inches|in|''|\"", "") %>% 
    str_replace("^([4-7])\\s*[,\\.\\s+]\\s*(\\d*)$", "\\1'\\2") 
```

***


### Assessment Part 1: String Processing Part 3

In this part of the assessment, you will answer several multiple choice questions that review the concepts of string processing. You can answer these questions without using R, although you may find it helpful to experiment with commands in your console.

In the second part of the assessment on the next page, you will import a real dataset and use string processing to clean it for analysis. This will require you to write code in R.

Want even more practice with regular expressions? Complete the lessons and exercises in the RegexOne online interactive tutorial!

***

#### **Question 1**  

```
s <- c("5'10", "6'1\"", "5'8inches", "5'7.5")
tab <- data.frame(x = s)
```
If you use the extract code from our video, the decimal point is dropped. What modification of the code would allow you to put the decimals in a third column called “decimal”?


```
extract(data = tab, col = x, into = c(“feet”, “inches”, “decimal”), 
regex = "(\\d)'(\\d{1,2})(\\.)?"
``` 
```
extract(data = tab, col = x, into = c("feet", "inches", "decimal"), 
regex = "(\\d)'(\\d{1,2})(\\.\\d+)" 
``` 

```
extract(data = tab, col = x, into = c("feet", "inches", "decimal"), 
regex = "(\\d)'(\\d{1,2})\\.\\d+?"
```
```
extract(data = tab, col = x, into = c("feet", "inches", "decimal"), 
regex = "(\\d)'(\\d{1,2})(\\.\\d+)?")    
```

#### **Question 2**  

You have the following data frame, schedule:
```
>schedule
day		staff
Monday		Mandy, Chris and Laura
Tuesday		Steve, Ruth and Frank
```
You want to turn this into a more useful data frame.

Which two commands would properly split the text in the “staff” column into each individual name? Select ALL that apply.


- str_split(schedule$staff, ",|and")
- str_split(schedule$staff, ", | and ")   [*]
- str_split(schedule$staff, ",\\s|\\sand\\s")   [*]
- str_split(schedule$staff, "\\s?(,|and)\\s?")

#### **Question 3**  

You have the following data frame, schedule:
```
> schedule
day         staff
Monday   	Mandy, Chris and Laura
Tuesday 	Steve, Ruth and Frank
```
What code would successfully turn your “Schedule” table into the following tidy table?

```
> tidy
day     staff
<chr>   <chr>
Monday  Mandy
Monday  Chris
Monday  Laura
Tuesday Steve
Tuesday Ruth 
Tuesday Frank
```
```
[*]
tidy <- schedule %>% 
  mutate(staff = str_split(staff, ", | and ")) %>% 
  unnest()
```

```
tidy <- separate(schedule, staff, into = c("s1","s2","s3"), sep = “,”) %>% 
  gather(key = s, value = staff, s1:s3)
```

```
tidy <- schedule %>% 
  mutate(staff = str_split(staff, ", | and ", simplify = TRUE)) %>% 
  unnest()
```

#### **Question 4**  

Using the gapminder data, you want to recode countries longer than 12 letters in the region “Middle Africa” to their abbreviations in a new column, “country_short”. Which code would accomplish this?


```
dat <- gapminder %>% filter(region == "Middle Africa") %>% 
  mutate(recode(country, 
                "Central African Republic" = "CAR", 
                "Congo, Dem. Rep." = "DRC",
                "Equatorial Guinea" = "Eq. Guinea"))
```
```
dat <- gapminder %>% filter(region == "Middle Africa") %>% 
  mutate(country_short = recode(country, 
                                c("Central African Republic", "Congo, Dem. Rep.", "Equatorial Guinea"),
                                c("CAR", "DRC", "Eq. Guinea")))
```
```
dat <- gapminder %>% filter(region == "Middle Africa") %>% 
  mutate(country = recode(country, 
                          "Central African Republic" = "CAR", 
                          "Congo, Dem. Rep." = "DRC",
                          "Equatorial Guinea" = "Eq. Guinea"))
```
```
[*]
dat <- gapminder %>% filter(region == "Middle Africa") %>% 
  mutate(country_short = recode(country, 
                                "Central African Republic" = "CAR", 
                                "Congo, Dem. Rep." = "DRC",
                                "Equatorial Guinea" = "Eq. Guinea"))
```

Import raw Brexit referendum polling data from Wikipedia:

library(rvest)
library(tidyverse)
library(stringr)
url <- "https://en.wikipedia.org/w/index.php?title=Opinion_polling_for_the_United_Kingdom_European_Union_membership_referendum&oldid=896735054"
tab <- read_html(url) %>% html_nodes("table")
polls <- tab[[5]] %>% html_table(fill = TRUE)
You will use a variety of string processing techniques learned in this section to reformat these data.

#### **Question 5**  

Some rows in this table do not contain polls. You can identify these by the lack of the percent sign (%) in the Remain column.

Update polls by changing the column names to c("dates", "remain", "leave", "undecided", "lead", "samplesize", "pollster", "poll_type", "notes") and only keeping rows that have a percent sign (%) in the remain column.

How many rows remain in the polls data frame?

```
names(polls) <- c("dates", "remain", "leave", "undecided", "lead", "samplesize", "pollster", "poll_type", "notes")
polls <- polls[str_detect(polls$remain, "%"), -9]
nrow(polls)
```

#### **Question 6**  

The remain and leave columns are both given in the format "48.1%": percentages out of 100% with a percent symbol.

Which of these commands converts the remain vector to a proportion between 0 and 1?
Check all correct answers.

- as.numeric(str_remove(polls$remain, "%"))
- as.numeric(polls$remain)/100
- parse_number(polls$remain)
- str_remove(polls$remain, "%")/100
- as.numeric(str_replace(polls$remain, "%", ""))/100    [*]
- parse_number(polls$remain)/100    [*]

#### **Question 7**  

The undecided column has some "N/A" values. These "N/A"s are only present when the remain and leave columns total 100%, so they should actually be zeros.

Use a function from stringr to convert "N/A" in the undecided column to 0. The format of your command should be function_name(polls$undecided, "arg1", "arg2").

What function replaces function_name?  
 str_replace_all  
What argument replaces arg1?  
N/A  
What argument replaces arg2? 0  

#### **Question 8**  

The dates column contains the range of dates over which the poll was conducted. The format is "8-10 Jan" where the poll had a start date of 2016-01-08 and end date of 2016-01-10. Some polls go across month boundaries (16 May-12 June).

The end date of the poll will always be one or two digits, followed by a space, followed by the month as one or more letters (either capital or lowercase). In these data, all month abbreviations or names have 3, 4 or 5 letters.

Write a regular expression to extract the end day and month from dates. Insert it into the skeleton code below:

```
temp <- str_extract_all(polls$dates, _____)
end_date <- sapply(temp, function(x) x[length(x)]) # take last element (handles polls that cross month boundaries)
```
Which of the following regular expressions correctly extracts the end day and month when inserted into the blank in the code above?

- "\\d?\\s[a-zA-Z]?"
- "\\d+\\s[a-zA-Z]+"    [*]
- "\\d+\\s[A-Z]+"
- "[0-9]+\\s[a-zA-Z]+"    [*]
- "\\d{1,2}\\s[a-zA-Z]+"    [*]
- "\\d{1,2}[a-zA-Z]+"
- "\\d+\\s[a-zA-Z]{3,5}"    [*]

